version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpass

  user_app:
    build:
      network: host
      context: ./
      dockerfile: Dockerfile

    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpass@postgres:5432/postgres

    ports:
      - 3000:3000
    depends_on:
      - postgres
